# frozen_string_literal: true

# Regenerates the RAR oracle fixtures under spec/fixtures/rar/oracle/.
#
# The specs that used to shell out to `unrar` now assert against these
# committed files, so CI never needs the rar/unrar oracle. When the
# writers legitimately change their output, run:
#
#   bundle exec ruby scripts/generate_rar_oracle_fixtures.rb
#
# and commit the refreshed fixtures. The script FAILS unless the local
# `unrar` oracle validates every generated archive, and unless each
# writer is byte-deterministic across two runs (the specs compare fresh
# writer output against these fixtures byte-for-byte).

require "digest"
require "fileutils"
require "tmpdir"

ROOT = File.expand_path("..", __dir__)
DEST = File.join(ROOT, "spec/fixtures/rar/oracle")
UNRAR = "unrar"
# RAR5 embeds mtime as epoch seconds; pin it so fixtures are reproducible
FIXED_TIME = Time.at(1_700_000_000)

def sh!(*cmd)
  system(*cmd) or abort("FAILED: #{cmd.join(' ')}")
end

def oracle_t(path)
  sh!(UNRAR, "t", "-idq", path)
end

def oracle_listing(path)
  out = `#{UNRAR} l #{path} 2>&1`
  abort("unrar l failed for #{path}:\n#{out}") if out.include?("ERROR") || $?.success? == false
  out
end

def build_rar5_single(dir)
  input = File.join(dir, "in.txt")
  File.binwrite(input, "Test content for unrar")
  archive = File.join(dir, "rar5_single.rar")
  writer = Omnizip::Formats::Rar::Rar5::Writer.new(archive)
  writer.add_file(input, "test.txt")
  writer.write
  archive
end

def build_rar4_store_tree(dir)
  big = File.join(dir, "big.txt")
  File.binwrite(big, "omnizip RAR4 interop fixture. " * 800)
  tree = File.join(dir, "tree")
  FileUtils.mkdir_p(File.join(tree, "sub"))
  File.binwrite(File.join(tree, "README.md"), "# tree\n")
  File.binwrite(File.join(tree, "sub", "main.rb"), "puts 'hi'\n")
  File.binwrite(File.join(tree, "empty.bin"), "")
  archive = File.join(dir, "rar4_store_tree.rar")
  writer = Omnizip::Formats::Rar::Writer.new(archive, compression: :store)
  writer.add_file(big)
  writer.add_directory(tree)
  writer.write
  archive
end

def build_rar5_multivolume(dir)
  %w[compat0.txt compat1.txt].each_with_index do |name, i|
    File.binwrite(File.join(dir, name), "Compatible content #{i}\n" * 3000)
  end
  archive = File.join(dir, "rar5_mv.rar")
  writer = Omnizip::Formats::Rar::Rar5::Writer.new(
    archive, multi_volume: true, volume_size: 65_536, compression: :store
  )
  writer.add_file(File.join(dir, "compat0.txt"))
  writer.add_file(File.join(dir, "compat1.txt"))
  volumes = writer.write
  raise "expected split volumes, got #{volumes.size}" unless volumes.size > 1

  volumes
end

def build_rar5_large(dir)
  archive = File.join(dir, "rar5_large.rar")
  writer = Omnizip::Formats::Rar5::Writer.new
  io = StringIO.new
  # RAR5 stores mtime as epoch seconds; the fixed constant keeps the bytes
  # reproducible across machines and timezones.
  writer.write_archive(io, [{ name: "large.txt", data: "X" * 10_000, time: FIXED_TIME }])
  File.binwrite(archive, io.string)
  archive
end

def build_rar5_store(dir)
  input = File.join(dir, "test.txt")
  File.write(input, "Test content for unrar")
  archive = File.join(dir, "rar5_store_omnizip.rar")
  writer = Omnizip::Formats::Rar::Rar5::Writer.new(archive, compression: :store)
  writer.add_file(input, "test.txt")
  writer.write
  archive
end

def build_rar5_lzss_fallback(dir)
  input = File.join(dir, "test.txt")
  File.write(input, "Test content for unrar")
  archive = File.join(dir, "rar5_lzss_fallback.rar")
  writer = Omnizip::Formats::Rar::Rar5::Writer.new(archive,
                                                   compression: :lzss, level: 3)
  writer.add_file(input, "test.txt")
  writer.write
  archive
end

def build_rar5_multi_files(dir)
  %w[file1.txt file2.txt].each_with_index do |name, i|
    File.write(File.join(dir, name), "Content #{i + 1}\n" * 10)
  end
  archive = File.join(dir, "rar5_multi_files.rar")
  writer = Omnizip::Formats::Rar::Rar5::Writer.new(archive,
                                                   compression: :lzma, level: 3)
  writer.add_file(File.join(dir, "file1.txt"), "file1.txt")
  writer.add_file(File.join(dir, "file2.txt"), "file2.txt")
  writer.write
  archive
end

builders = {
  "rar5_single" => method(:build_rar5_single),
  "rar4_store_tree" => method(:build_rar4_store_tree),
  "rar5_multivolume" => method(:build_rar5_multivolume),
  "rar5_large" => method(:build_rar5_large),
  "rar5_store_omnizip" => method(:build_rar5_store),
  "rar5_lzss_fallback" => method(:build_rar5_lzss_fallback),
  "rar5_multi_files" => method(:build_rar5_multi_files),
}

abort("unrar oracle not available — these fixtures can only be regenerated where unrar exists") unless system("which #{UNRAR} > /dev/null 2>&1")
require "omnizip"

FileUtils.mkdir_p(DEST)
manifest = ["# RAR oracle fixtures — regenerated by scripts/generate_rar_oracle_fixtures.rb",
            "# (unrar validated each archive at generation time; specs assert against these bytes)",
            "generated: #{Time.now.utc.iso8601}",
            "unrar_version: (derived from the first frozen listing's banner)",
            "fixtures:"]

builders.each do |name, builder|
  puts "== #{name}"
  Dir.mktmpdir("rar_oracle") do |dir|
    built1 = builder.call(dir)
    h1 = Array(built1).map { |p| Digest::SHA256.file(p).hexdigest }
    h2 = Dir.mktmpdir("rar_oracle2") do |dir2|
      Array(builder.call(dir2)).map { |p| Digest::SHA256.file(p).hexdigest }
    end
    abort("#{name}: writer not byte-deterministic across runs") unless h1 == h2

    first = Array(built1).first
    oracle_t(first)
    listing = oracle_listing(first)
    digest_pairs = Array(built1).zip(h1).map do |path, h|
      base = name == "rar5_multivolume" ? File.basename(path) : "#{name}.rar"
      dest = File.join(DEST, base)
      FileUtils.cp(path, dest)
      manifest << "  - file: #{base}"
      manifest << "    sha256: #{h}"
      base
    end
    listing_name = "#{name}.unrar-l.txt"
    File.write(File.join(DEST, listing_name), listing)
    manifest << "  - file: #{listing_name}"
    manifest << "    oracle_listing_of: #{digest_pairs.first}"
    puts "   frozen: #{digest_pairs.join(', ')}"
  end
end

File.write(File.join(DEST, "MANIFEST.yml"), "#{manifest.join("\n")}\n")
puts "done → #{DEST}"
